image: gitpod/workspace-full:2023-02-27-14-39-56
tasks:
  - name: 1_producer
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
    init: | 
      pip install -r /workspace/workshop-realtime-data-pipelines/requirements.txt >> ./install.log
      cd /workspace/workshop-realtime-data-pipelines/tools
      wget https://github.com/datastax/pulsar/releases/download/ls210_1.1/lunastreaming-shell-2.10.1.1-bin.tar.gz \
          && tar xvzf lunastreaming-shell-2.10.1.1-bin.tar.gz >> ./install.log \
          && rm -f lunastreaming-shell-2.10.1.1-bin.tar.gz
      clear
      cd /workspace/workshop-realtime-data-pipelines
    command: |
      unset JAVA_TOOL_OPTIONS
      source /home/gitpod/.astra/cli/astra-init.sh
      export PYTHONPATH="/workspace/workshop-realtime-data-pipelines/:$PYTHONPATH"
      gp preview --external https://astra.dev/yt-9-14
      astra setup
  - name: 2_consumer
    command: |
      unset JAVA_TOOL_OPTIONS
      export PYTHONPATH="/workspace/workshop-realtime-data-pipelines/:$PYTHONPATH"
      source /home/gitpod/.astra/cli/astra-init.sh
      clear
      echo "***************"
      echo "** Consumer ***"
      echo "***************"
  - name: 3_analyzer
    command: |
      unset JAVA_TOOL_OPTIONS
      export PYTHONPATH="/workspace/workshop-realtime-data-pipelines/:$PYTHONPATH"
      source /home/gitpod/.astra/cli/astra-init.sh
      clear
      echo "***************"
      echo "** Analyzer ***"
      echo "***************"
  - name: 4_reader
    command: |
      unset JAVA_TOOL_OPTIONS
      export PYTHONPATH="/workspace/workshop-realtime-data-pipelines/:$PYTHONPATH"
      source /home/gitpod/.astra/cli/astra-init.sh
      clear
      echo "***************"
      echo "** Analyzer ***"
      echo "***************"
  - name: 5_database
    command: |
      unset JAVA_TOOL_OPTIONS
      export PYTHONPATH="/workspace/workshop-realtime-data-pipelines/:$PYTHONPATH"
      source /home/gitpod/.astra/cli/astra-init.sh
      clear
      echo "***************"
      echo "** Analyzer ***"
      echo "***************"           
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
  
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
